<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="16" hostname="Ameet" failures="1" tests="2" name="Default test" time="13.042" errors="0" timestamp="2024-11-11T16:19:33 IST">
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="createAppointmentTest" time="12.842">
    <failure type="java.lang.AssertionError" message="Status should be OK. expected [OK] but found [Failed]">
      <![CDATA[java.lang.AssertionError: Status should be OK. expected [OK] but found [Failed]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testcases.RestAssured_TestCases_PL1.createAppointmentTest(RestAssured_TestCases_PL1.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createAppointmentTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="cancelAppointmentTest" time="0.0">
    <skipped/>
  </testcase> <!-- cancelAppointmentTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="getAllApplicableDoctors" time="0.0">
    <ignored/>
  </testcase> <!-- getAllApplicableDoctors -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="findMatchingPatientTest" time="0.0">
    <ignored/>
  </testcase> <!-- findMatchingPatientTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="BookingListTest" time="0.0">
    <ignored/>
  </testcase> <!-- BookingListTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="DeactivatePharmCountTest" time="0.0">
    <ignored/>
  </testcase> <!-- DeactivatePharmCountTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="AllStockDetailsTest" time="0.0">
    <ignored/>
  </testcase> <!-- AllStockDetailsTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="getAllRegisteredPatientsTest" time="0.0">
    <ignored/>
  </testcase> <!-- getAllRegisteredPatientsTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="searchPatientTest" time="0.0">
    <ignored/>
  </testcase> <!-- searchPatientTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="getAllBillingCounters" time="0.0">
    <ignored/>
  </testcase> <!-- getAllBillingCounters -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="MainStoreTest" time="0.0">
    <ignored/>
  </testcase> <!-- MainStoreTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="ActivatePharmCountTest" time="0.0">
    <ignored/>
  </testcase> <!-- ActivatePharmCountTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="PatientConsumptionTest" time="0.0">
    <ignored/>
  </testcase> <!-- PatientConsumptionTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="PharmacyStoreTest" time="0.0">
    <ignored/>
  </testcase> <!-- PharmacyStoreTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="addcurrencyTest" time="0.0">
    <ignored/>
  </testcase> <!-- addcurrencyTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="clashAppointmentTest" time="0.0">
    <ignored/>
  </testcase> <!-- clashAppointmentTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="AdmittedPatientsData" time="0.0">
    <ignored/>
  </testcase> <!-- AdmittedPatientsData -->
  <testcase classname="testcases.RestAssured_TestCases_PL1" name="AppointApplicDeptTest" time="0.0">
    <ignored/>
  </testcase> <!-- AppointApplicDeptTest -->
</testsuite> <!-- Default test -->
